function lbincrements = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  LBINCREMENTS = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  LBINCREMENTS = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  lbincrements = importfile("C:\Users\panit\Desktop\Structures Lab 2\5lbincrements.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 23-Feb-2020 19:16:29

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["LoadingCaselbs", "F0lbf", "F1lbf", "F2lbf", "F3Dlbf", "LVDTin", "PM"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "PM", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "PM", "EmptyFieldRule", "auto");

% Import the data
lbincrements = readtable(filename, opts);

end